import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion, useInView } from 'framer-motion';
import { ArrowUpRight, ArrowRight, Menu, X, ChevronDown } from 'lucide-react';
import './styles.css';

const events = [
  {id:'01',slug:'neural-quiz', title:'NEURAL//QUIZ', kind:'technical', desc:'Think at the speed of signal.', format:'DUO / 2 MINDS', hue:'crimson'},
  {id:'02',slug:'promptforge', title:'PROMPTFORGE', kind:'technical', desc:'Shape intelligence into impact.', format:'SOLO / OPEN TOOLS', hue:'steel'},
  {id:'03',slug:'mystery-code', title:'MYSTERY_CODE', kind:'technical', desc:'The solution is hiding in plain sight.', format:'DUO / 90 MIN', hue:'tunnel'},
  {id:'04',slug:'signal-hunt', title:'SIGNAL//HUNT', kind:'non-technical', desc:'Track the anomaly. Claim the arena.', format:'SQUAD / 4 PLAYERS', hue:'architecture'},
  {id:'05',slug:'frame-shift', title:'FRAME_SHIFT', kind:'non-technical', desc:'Create the moment no one forgets.', format:'TEAM / 3 MINUTES', hue:'light'},
  {id:'06',slug:'paper-pulse', title:'PAPER//PULSE', kind:'technical', desc:'Ideas with enough gravity to move rooms.', format:'SOLO / PRESENTATION', hue:'void'},
];
const schedule = [['09:00','GATES OPEN','Registration & system check'],['10:00','OPENING SIGNAL','Inauguration'],['10:30','THE BATTLEGROUND','Technical arenas activate'],['13:00','INTERMISSION','Lunch / network'],['14:00','SECOND WAVE','Creative arenas'],['17:30','FINAL FREQUENCY','Results & valedictory']];

function Tech({number, className=''}) { return <div className={`tech ${className}`}><span>{number}</span><i/><b>SYS//ACTIVE</b><em>12°48' / 80°12'</em></div> }
function Reveal({children, className=''}) { return <motion.div className={className} initial={{opacity:0,y:32}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.18}} transition={{duration:.7,ease:[.22,1,.36,1]}}>{children}</motion.div> }
function Loader({done}) { return <AnimatePresence>{!done && <motion.div className="loader" exit={{opacity:0,transition:{duration:.45}}}><p>DEPT. OF INFORMATION TECHNOLOGY // 2026</p><h1>ZYNORA<span>’26</span></h1><div className="loadline"><motion.i initial={{scaleX:0}} animate={{scaleX:1}} transition={{duration:1.2,ease:'easeInOut'}}/></div><small>INITIALIZING EXPERIENCE <b>100%</b></small></motion.div>}</AnimatePresence> }
function Navbar({open,setOpen,detail=false}) { const [scrolled,setScrolled]=useState(false);useEffect(()=>{const check=()=>setScrolled(scrollY>18);check();addEventListener('scroll',check,{passive:true});return()=>removeEventListener('scroll',check)},[]);const to=id=>detail?`/#${id}`:`#${id}`;return <nav className={scrolled?'is-scrolled':''}><a className="logo" href={to('top')}>ZYNORA<sup>’26</sup></a><div className="navlinks"><a href={to('top')} className="selected">HOME</a><a href={to('events')}>EVENTS</a><a href={to('schedule')}>SCHEDULE</a><a href={to('about')}>ABOUT</a></div><a className="register small-register" href={to('register')}>REGISTER <ArrowUpRight size={15}/></a><button className="menu" onClick={()=>setOpen(!open)} aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open}>{open?<X/>:<Menu/>}</button></nav> }
function Cursor(){const [visible,setVisible]=useState(false);useEffect(()=>{if(matchMedia('(pointer:coarse)').matches)return;const move=e=>{document.documentElement.style.setProperty('--cursor-x',`${e.clientX}px`);document.documentElement.style.setProperty('--cursor-y',`${e.clientY}px`);setVisible(true)};addEventListener('pointermove',move);return()=>removeEventListener('pointermove',move)},[]);return <div className={`cursor ${visible?'cursor-on':''}`} aria-hidden="true"><i/><b/></div>}
function MobileMenu({open,setOpen,detail=false}) { const to=id=>detail?`/#${id}`:`#${id}`;return <AnimatePresence>{open && <motion.div className="mobile-menu" initial={{clipPath:'inset(0 0 100% 0)'}} animate={{clipPath:'inset(0 0 0% 0)'}} exit={{clipPath:'inset(0 0 100% 0)'}}><p>MENU // 01–04</p>{['HOME','EVENTS','SCHEDULE','ABOUT'].map((x,i)=><a onClick={()=>setOpen(false)} href={to(x==='HOME'?'top':x.toLowerCase())} key={x}><sup>0{i+1}</sup>{x}<ArrowUpRight/></a>)}<span>CHENNAI // INDIA<br/>FEB 20—21, 2026</span></motion.div>}</AnimatePresence> }
function Hero(){ return <section id="top" className="hero"><div className="architecture"><div className="sun"/><div className="tower left"/><div className="tower center"/><div className="tower right"/><div className="floor"/><div className="figure"/></div><div className="scan"/><div className="hero-copy"><motion.p initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{delay:1.3}}>DEPARTMENT OF INFORMATION TECHNOLOGY <i/> PRESENTS</motion.p><motion.h1 initial={{clipPath:'inset(0 0 100% 0)'}} animate={{clipPath:'inset(0 0 0 0)'}} transition={{delay:1.45,duration:.9,ease:[.22,1,.36,1]}}>ZYNORA<sup>’26</sup></motion.h1><motion.div className="hero-bottom" initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:1.8}}><div><strong>IT WAS INCOMPLETE<br/>WITHOUT US.</strong><p>IDEAS &nbsp; CODE &nbsp; PEOPLE &nbsp; BEYOND</p></div><div className="hero-intro">A SYMPOSIUM FOR THE NEXT<br/>GENERATION OF THINKERS.</div></motion.div><motion.a href="#events" className="explore" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:2.1}}>EXPLORE EVENTS <ArrowRight/></motion.a></div><Tech number="00" className="hero-tech"/><a className="scroll" href="#events">SCROLL TO EXPLORE <ChevronDown size={15}/></a></section> }
function SectionTitle({no,children,eyebrow}){return <Reveal className="section-title"><span>{no}</span><p>{eyebrow}</p><h2>{children}</h2></Reveal>}
function EventCard({event}) { return <motion.article layout className={`event-card ${event.hue}`} initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.96}} transition={{duration:.35}}><div className="event-image"><span>{event.id}</span><div className="image-shape"/><b>⌖</b></div><div className="event-info"><small>{event.kind} // {event.format}</small><h3>{event.title}</h3><p>{event.desc}</p><a href={`/events/${event.slug}`}>MORE INFO <ArrowUpRight size={15}/></a></div></motion.article>}
function Events(){const [filter,setFilter]=useState('all'); return <section id="events" className="events"><Tech number="01"/><SectionTitle no="01" eyebrow="THE BATTLEGROUND">FIND YOUR<br/><i>ARENA.</i></SectionTitle><div className="event-head"><p>Every discipline has a collision point.<br/>Choose yours and enter the system.</p><div className="filters">{['all','technical','non-technical'].map(f=><button type="button" aria-pressed={filter===f} onClick={()=>setFilter(f)} className={filter===f?'active':''} key={f}>{f==='all'?'ALL':f.toUpperCase()}</button>)}</div></div><motion.div layout className="event-grid"><AnimatePresence mode="popLayout">{events.filter(e=>filter==='all'||e.kind===filter).map(e=><EventCard event={e} key={e.id}/>)}</AnimatePresence></motion.div></section>}
function Metrics(){return <section className="metrics"><Reveal><p>THE NUMBERS DON'T<br/>TELL THE WHOLE STORY.</p></Reveal><div>{[['08','ARENAS'],['500+','MINDS'],['02','DAYS'],['∞','OUTCOMES']].map(([n,l])=><Reveal key={l} className="metric"><b>{n}</b><span>{l}</span></Reveal>)}</div></section>}
function About(){return <section id="about" className="about"><Tech number="02"/><Reveal><p className="eyebrow">NOT JUST AN EVENT.</p><h2>AN <i>EXPERIENCE</i><br/>IN MOTION.</h2></Reveal><Reveal className="about-copy"><p>Zynora is where future technologists meet the beautiful mess of possibility. A two-day collision of sharp ideas, creative courage and the people willing to build what comes next.</p><a href="#register" className="text-link">ENTER THE ARENA <ArrowRight/></a></Reveal><div className="about-orbit"><span>TECHNOLOGY</span><span>CREATIVITY</span><span>COLLISION</span><b>Z<br/>26</b><span>PEOPLE</span><span>IDEAS</span></div></section>}
function Schedule(){return <section id="schedule" className="schedule"><SectionTitle no="03" eyebrow="PROGRAM / 20.02.26">THE DAY<br/>IN <i>FREQUENCY.</i></SectionTitle><div className="timeline">{schedule.map(([time,title,detail],i)=><Reveal className="slot" key={time}><time>{time}</time><span>0{i+1}</span><div><h3>{title}</h3><p>{detail}</p></div></Reveal>)}</div></section>}
function Register(){const [sent,setSent]=useState(false);return <section id="register" className="registration"><Tech number="04"/><Reveal><p className="eyebrow">YOUR SIGNAL IS WAITING</p><h2>CLAIM YOUR<br/><i>PLACE.</i></h2></Reveal><Reveal className="registration-card">{sent?<div className="success" role="status"><small>TRANSMISSION RECEIVED</small><h3>YOU'RE ON THE GRID.</h3><p>We'll send your arena coordinates soon.</p></div>:<form aria-label="Symposium registration" onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="form-count">01 <span>PERSONAL DETAILS</span></div><label>NAME<input required placeholder="YOUR FULL NAME"/></label><label>EMAIL<input required type="email" placeholder="YOU@EXAMPLE.COM"/></label><label>SELECT ARENA<select required defaultValue=""><option disabled value="">CHOOSE YOUR EVENT</option>{events.map(e=><option key={e.id}>{e.title}</option>)}</select></label><button className="register submit">TRANSMIT REGISTRATION <ArrowUpRight/></button></form>}</Reveal></section>}
function Footer(){return <footer><div className="footer-title">SEE YOU<br/>AT THE <i>ARENA.</i></div><div className="foot-info"><p>ZYNORA ’26<br/>DEPT. OF INFORMATION TECHNOLOGY</p><p>FEB 20—21 / 2026<br/>CHENNAI, INDIA</p><p>INSTAGRAM ↗<br/>LINKEDIN ↗</p></div><small>© 2026 ZYNORA // MADE FOR WHAT'S NEXT</small></footer>}
function EventDetail({event}){const [menu,setMenu]=useState(false);return <><Cursor/><Navbar detail open={menu} setOpen={setMenu}/><MobileMenu detail open={menu} setOpen={setMenu}/><main className="detail"><a href="/#events" className="back">← BACK TO EVENTS</a><div className={`detail-visual ${event.hue}`}><div className="image-shape"/><span>{event.id} // {event.kind.toUpperCase()} EVENT</span></div><section className="detail-copy"><p className="eyebrow">// {event.kind.toUpperCase()} EVENT</p><h1>{event.title}</h1><strong>{event.desc}</strong><p>Enter a tightly designed arena where fast decisions, clear thinking and fearless collaboration decide the outcome. Bring your best signal.</p><div className="detail-meta"><div><small>PARTICIPATION</small>{event.format}</div><div><small>DURATION</small>90 MINUTES</div><div><small>TOOLS</small>YOUR BEST WORK</div></div><h2>HOW IT<br/><i>WORKS.</i></h2><ol><li>REGISTER YOUR SIGNAL</li><li>RECEIVE THE BRIEF</li><li>ENTER THE ARENA</li><li>MAKE IT COUNT</li></ol><a className="register" href="/#register">REGISTER FOR THIS EVENT <ArrowUpRight/></a></section></main><Footer/></>}
function App(){const [loaded,setLoaded]=useState(false),[menu,setMenu]=useState(false);useEffect(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let t=setTimeout(()=>setLoaded(true),reduced?0:1450);return()=>clearTimeout(t)},[]);const match=location.pathname.match(/^\/events\/([^/]+)/);const event=match&&events.find(e=>e.slug===match[1]);if(event)return <EventDetail event={event}/>; return <><Loader done={loaded}/><Cursor/><Navbar open={menu} setOpen={setMenu}/><MobileMenu open={menu} setOpen={setMenu}/><main><Hero/><Events/><Metrics/><About/><Schedule/><Register/></main><Footer/></>}
createRoot(document.getElementById('root')).render(<App/>);
